IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WARESUM_WARECODE]') AND type = 'F')
ALTER TABLE [WARESUM]  WITH CHECK ADD  CONSTRAINT [FK_WARESUM_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WARESUM_WARECODE]') AND type = 'F')
ALTER TABLE [WARESUM] CHECK CONSTRAINT [FK_WARESUM_WARECODE]
