IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_CUSTFIRST_WARECODE]') AND type = 'F')
ALTER TABLE [CUSTFIRST]  WITH CHECK ADD  CONSTRAINT [FK_CUSTFIRST_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_CUSTFIRST_WARECODE]') AND type = 'F')
ALTER TABLE [CUSTFIRST] CHECK CONSTRAINT [FK_CUSTFIRST_WARECODE]
