IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_INCOMECURR_CUSTOMER]') AND type = 'F')
ALTER TABLE [INCOMECURR]  WITH CHECK ADD  CONSTRAINT [FK_INCOMECURR_CUSTOMER] FOREIGN KEY([custno])
REFERENCES [CUSTOMER] ([code])
ON UPDATE CASCADE
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_INCOMECURR_CUSTOMER]') AND type = 'F')
ALTER TABLE [INCOMECURR] CHECK CONSTRAINT [FK_INCOMECURR_CUSTOMER]
