IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_NEARSALE_WARECODE]') AND type = 'F')
ALTER TABLE [NEARSALE]  WITH CHECK ADD  CONSTRAINT [FK_NEARSALE_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_NEARSALE_WARECODE]') AND type = 'F')
ALTER TABLE [NEARSALE] CHECK CONSTRAINT [FK_NEARSALE_WARECODE]
