IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WAREALLOTM_WARECODE]') AND type = 'F')
ALTER TABLE [WAREALLOTM]  WITH CHECK ADD  CONSTRAINT [FK_WAREALLOTM_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WAREALLOTM_WARECODE]') AND type = 'F')
ALTER TABLE [WAREALLOTM] CHECK CONSTRAINT [FK_WAREALLOTM_WARECODE]
