IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WAREOUTM_WARECODE]') AND type = 'F')

ALTER TABLE [WAREOUTM]  WITH CHECK ADD  CONSTRAINT [FK_WAREOUTM_WARECODE] FOREIGN KEY([wareno])

REFERENCES [WARECODE] ([wareno])

ON UPDATE CASCADE

ON DELETE CASCADEIF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WAREOUTM_WARECODE]') AND type = 'F')

ALTER TABLE [WAREOUTM] CHECK CONSTRAINT [FK_WAREOUTM_WARECODE]