IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WAREINM_WARECODE]') AND type = 'F')

ALTER TABLE [WAREINM]  WITH CHECK ADD  CONSTRAINT [FK_WAREINM_WARECODE] FOREIGN KEY([wareno])

REFERENCES [WARECODE] ([wareno])

ON UPDATE CASCADE

ON DELETE CASCADEIF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WAREINM_WARECODE]') AND type = 'F')

ALTER TABLE [WAREINM] CHECK CONSTRAINT [FK_WAREINM_WARECODE]