IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_REFUNDINM_WARECODE]') AND type = 'F')

ALTER TABLE [REFUNDINM]  WITH CHECK ADD  CONSTRAINT [FK_REFUNDINM_WARECODE] FOREIGN KEY([wareno])

REFERENCES [WARECODE] ([wareno])

ON UPDATE CASCADE

ON DELETE CASCADEIF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_REFUNDINM_WARECODE]') AND type = 'F')

ALTER TABLE [REFUNDINM] CHECK CONSTRAINT [FK_REFUNDINM_WARECODE]