IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_REFUNDOUTH_CUSTOMER]') AND type = 'F')

ALTER TABLE [REFUNDOUTH]  WITH CHECK ADD  CONSTRAINT [FK_REFUNDOUTH_CUSTOMER] FOREIGN KEY([custno])

REFERENCES [CUSTOMER] ([code])

ON UPDATE CASCADEIF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_REFUNDOUTH_CUSTOMER]') AND type = 'F')

ALTER TABLE [REFUNDOUTH] CHECK CONSTRAINT [FK_REFUNDOUTH_CUSTOMER]