IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WAREOUTH_CUSTOMER]') AND type = 'F')

ALTER TABLE [WAREOUTH]  WITH CHECK ADD  CONSTRAINT [FK_WAREOUTH_CUSTOMER] FOREIGN KEY([custno])

REFERENCES [CUSTOMER] ([code])

ON UPDATE CASCADEIF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_WAREOUTH_CUSTOMER]') AND type = 'F')

ALTER TABLE [WAREOUTH] CHECK CONSTRAINT [FK_WAREOUTH_CUSTOMER]