IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_NEARBUY_WARECODE]') AND type = 'F')

ALTER TABLE [NEARBUY]  WITH CHECK ADD  CONSTRAINT [FK_NEARBUY_WARECODE] FOREIGN KEY([wareno])

REFERENCES [WARECODE] ([wareno])

ON UPDATE CASCADE

ON DELETE CASCADEIF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK_NEARBUY_WARECODE]') AND type = 'F')

ALTER TABLE [NEARBUY] CHECK CONSTRAINT [FK_NEARBUY_WARECODE]