IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREALLOTM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WAREALLOTM]'))
ALTER TABLE [WAREALLOTM]  WITH CHECK ADD  CONSTRAINT [FK_WAREALLOTM_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREALLOTM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WAREALLOTM]'))
ALTER TABLE [WAREALLOTM] CHECK CONSTRAINT [FK_WAREALLOTM_WARECODE]
