IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_INCOMEBAL_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[INCOMEBAL]'))
ALTER TABLE [INCOMEBAL] DROP CONSTRAINT [FK_INCOMEBAL_CUSTOMER]
