IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREOUTH_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[WAREOUTH]'))
ALTER TABLE [WAREOUTH] DROP CONSTRAINT [FK_WAREOUTH_CUSTOMER]
