IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_CUSTGROUPM_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[CUSTGROUPM]'))
ALTER TABLE [CUSTGROUPM] DROP CONSTRAINT [FK_CUSTGROUPM_CUSTOMER]
