IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_REFUNDINM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[REFUNDINM]'))
ALTER TABLE [REFUNDINM] DROP CONSTRAINT [FK_REFUNDINM_WARECODE]
