IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WARECHECKM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WARECHECKM]'))
ALTER TABLE [WARECHECKM] DROP CONSTRAINT [FK_WARECHECKM_WARECODE]
