IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREOUTM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WAREOUTM]'))
ALTER TABLE [WAREOUTM] DROP CONSTRAINT [FK_WAREOUTM_WARECODE]
