IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_REFUNDINM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[REFUNDINM]'))
ALTER TABLE [REFUNDINM]  WITH CHECK ADD  CONSTRAINT [FK_REFUNDINM_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_REFUNDINM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[REFUNDINM]'))
ALTER TABLE [REFUNDINM] CHECK CONSTRAINT [FK_REFUNDINM_WARECODE]
