IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_CUSTFIRST_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[CUSTFIRST]'))
ALTER TABLE [CUSTFIRST]  WITH NOCHECK ADD  CONSTRAINT [FK_CUSTFIRST_CUSTOMER] FOREIGN KEY([code])
REFERENCES [CUSTOMER] ([code])
ON UPDATE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_CUSTFIRST_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[CUSTFIRST]'))
ALTER TABLE [CUSTFIRST] CHECK CONSTRAINT [FK_CUSTFIRST_CUSTOMER]
