IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_NEARBUY_WARECODE]') AND parent_object_id = OBJECT_ID(N'[NEARBUY]'))
ALTER TABLE [NEARBUY]  WITH CHECK ADD  CONSTRAINT [FK_NEARBUY_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_NEARBUY_WARECODE]') AND parent_object_id = OBJECT_ID(N'[NEARBUY]'))
ALTER TABLE [NEARBUY] CHECK CONSTRAINT [FK_NEARBUY_WARECODE]
