IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WARESUM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WARESUM]'))
ALTER TABLE [WARESUM]  WITH CHECK ADD  CONSTRAINT [FK_WARESUM_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WARESUM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WARESUM]'))
ALTER TABLE [WARESUM] CHECK CONSTRAINT [FK_WARESUM_WARECODE]
