IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_REFUNDOUTH_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[REFUNDOUTH]'))
ALTER TABLE [REFUNDOUTH] DROP CONSTRAINT [FK_REFUNDOUTH_CUSTOMER]
