IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_INCOMEBAL_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[INCOMEBAL]'))
ALTER TABLE [INCOMEBAL]  WITH CHECK ADD  CONSTRAINT [FK_INCOMEBAL_CUSTOMER] FOREIGN KEY([code])
REFERENCES [CUSTOMER] ([code])
ON UPDATE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_INCOMEBAL_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[INCOMEBAL]'))
ALTER TABLE [INCOMEBAL] CHECK CONSTRAINT [FK_INCOMEBAL_CUSTOMER]
