IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_CUSTFIRST_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[CUSTFIRST]'))
ALTER TABLE [CUSTFIRST] DROP CONSTRAINT [FK_CUSTFIRST_CUSTOMER]
