IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREALLOTM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WAREALLOTM]'))
ALTER TABLE [WAREALLOTM] DROP CONSTRAINT [FK_WAREALLOTM_WARECODE]
