IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_REFUNDOUTM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[REFUNDOUTM]'))
ALTER TABLE [REFUNDOUTM]  WITH CHECK ADD  CONSTRAINT [FK_REFUNDOUTM_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_REFUNDOUTM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[REFUNDOUTM]'))
ALTER TABLE [REFUNDOUTM] CHECK CONSTRAINT [FK_REFUNDOUTM_WARECODE]
