IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_NEARBUY_WARECODE]') AND parent_object_id = OBJECT_ID(N'[NEARBUY]'))
ALTER TABLE [NEARBUY] DROP CONSTRAINT [FK_NEARBUY_WARECODE]
