IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_REFUNDOUTH_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[REFUNDOUTH]'))
ALTER TABLE [REFUNDOUTH]  WITH CHECK ADD  CONSTRAINT [FK_REFUNDOUTH_CUSTOMER] FOREIGN KEY([custno])
REFERENCES [CUSTOMER] ([code])
ON UPDATE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_REFUNDOUTH_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[REFUNDOUTH]'))
ALTER TABLE [REFUNDOUTH] CHECK CONSTRAINT [FK_REFUNDOUTH_CUSTOMER]
