IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PROVFIRST_WARECODE]') AND parent_object_id = OBJECT_ID(N'[PROVFIRST]'))
ALTER TABLE [PROVFIRST] DROP CONSTRAINT [FK_PROVFIRST_WARECODE]
