IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_CUSTGROUPM_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[CUSTGROUPM]'))
ALTER TABLE [CUSTGROUPM]  WITH CHECK ADD  CONSTRAINT [FK_CUSTGROUPM_CUSTOMER] FOREIGN KEY([code])
REFERENCES [CUSTOMER] ([code])
ON UPDATE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_CUSTGROUPM_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[CUSTGROUPM]'))
ALTER TABLE [CUSTGROUPM] CHECK CONSTRAINT [FK_CUSTGROUPM_CUSTOMER]
