IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREOUTH_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[WAREOUTH]'))
ALTER TABLE [WAREOUTH]  WITH CHECK ADD  CONSTRAINT [FK_WAREOUTH_CUSTOMER] FOREIGN KEY([custno])
REFERENCES [CUSTOMER] ([code])
ON UPDATE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREOUTH_CUSTOMER]') AND parent_object_id = OBJECT_ID(N'[WAREOUTH]'))
ALTER TABLE [WAREOUTH] CHECK CONSTRAINT [FK_WAREOUTH_CUSTOMER]
