IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_REFUNDOUTM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[REFUNDOUTM]'))
ALTER TABLE [REFUNDOUTM] DROP CONSTRAINT [FK_REFUNDOUTM_WARECODE]
