IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_GROUPM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[GROUPM]'))
ALTER TABLE [GROUPM] DROP CONSTRAINT [FK_GROUPM_WARECODE]
