IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_GROUPM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[GROUPM]'))
ALTER TABLE [GROUPM]  WITH CHECK ADD  CONSTRAINT [FK_GROUPM_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_GROUPM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[GROUPM]'))
ALTER TABLE [GROUPM] CHECK CONSTRAINT [FK_GROUPM_WARECODE]
