IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PROVFIRST_WARECODE]') AND parent_object_id = OBJECT_ID(N'[PROVFIRST]'))
ALTER TABLE [PROVFIRST]  WITH CHECK ADD  CONSTRAINT [FK_PROVFIRST_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_PROVFIRST_WARECODE]') AND parent_object_id = OBJECT_ID(N'[PROVFIRST]'))
ALTER TABLE [PROVFIRST] CHECK CONSTRAINT [FK_PROVFIRST_WARECODE]
