IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREINM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WAREINM]'))
ALTER TABLE [WAREINM] DROP CONSTRAINT [FK_WAREINM_WARECODE]
