IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREOUTM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WAREOUTM]'))
ALTER TABLE [WAREOUTM]  WITH CHECK ADD  CONSTRAINT [FK_WAREOUTM_WARECODE] FOREIGN KEY([wareno])
REFERENCES [WARECODE] ([wareno])
ON UPDATE CASCADE
ON DELETE CASCADE
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WAREOUTM_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WAREOUTM]'))
ALTER TABLE [WAREOUTM] CHECK CONSTRAINT [FK_WAREOUTM_WARECODE]
