IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[FK_WARECOST_WARECODE]') AND parent_object_id = OBJECT_ID(N'[WARECOST]'))
ALTER TABLE [WARECOST] DROP CONSTRAINT [FK_WARECOST_WARECODE]
